### ISSUE TITLE
Log response body (maybe optional, with a parameter)

### ISSUE THREAD

**Issue by mkhanal** [sirrodgepodge/morgan-body#1]

**Comment by sirrodgepodge** [comment]
hmm good idea, I seem to remember looking into doing this and finding it difficult, the one way I can think of is wrapping express methods... which might not be the worst thing in the world, will take a look tonight

**Comment by sirrodgepodge** [comment]
okay, so a bit late, but tried this snippet out and it will work I think, should I include some sort of warning at startup time about using this in production you think?  Maybe it's obvious, just want to make sure I don't wreck anyone's day:

```js
app.use(function (req, res, next) {
  const originalSend = res.send;
  res.send = responseBeingSent => {
    let logResponse;
    if (responseBeingSent && !(responseBeingSent instanceof Buffer(  && typeof responseBeingSent === 'object') {
       try {
         logResponse = JSON.stringify(req.body, null, '\t').split('\n').forEach(line => console.log('\x1b[97m' + line + '\x1b[0m')); // needed for multi-line coloring
       } catch(e) {}
    } else if (typeof responseBeingSent === 'string') {
       logResponse = responseBeingSent;
    }
    if(logResponse) console.log(logResponse);
    originalSend.call(res, responseBeingSent);
  });
  next();
};
```

**Comment by mkhanal** [comment]
Maybe a safer way to do it would be to handle as part of the after hook.

```
server.on('after', morganLogger.log({responseBody: true/false, requestBody: true/false}) 
```
This removes our requirement to use the immediate mode i.e. _{immediate: true}_, because everyone can just hook it whereever they want in the middleware chain.

So an immediate mode will become

```
server.use(morganLogger.log({responseBody: false, requestBody: true/false}) 
//responseBody is irrelevant  because there is no response till now
```

I understand this would create certain change to the existing codebase. I'm happy to help if needed.
What do you think?

**Comment by sirrodgepodge** [comment]
this looks great actually, didn't know this was possible, was trying to find documentation for the 'after' event, are you sure that this exists?

**Comment by sirrodgepodge** [comment]
okay haha, went ahead and did this, perhaps not in the ideal way but it works quite well, see #2 and let me know what you think

**Comment by mkhanal** [comment]
This seems to work for what we want. I'm very surprised that we have to go through all this in express. I would have expected express to expose an event for when a response is send.

Why don't you merge it and i'll try to add it to my app. See if the decoration of res.send works without any issues

**Comment by sirrodgepodge** [comment]
k, did it and version bumped npm package to `0.10.0`
