### ISSUE TITLE
Colors are hard to read over a black terminal

### ISSUE THREAD

**Issue by ohadnav** [sirrodgepodge/morgan-body#12]
For example request body is almost black.

Could you create a "dracula theme" colors scheme?

Big thanks.

**Comment by sirrodgepodge** [comment]
Hm, thank you for letting me know, can you attach a screenshot and say what your OS is?

The Request Body is actually supposed to be ANSII’s white (the literal text “Request Body” is supposed to be pink, the body content white)

**Comment by sirrodgepodge** [comment]
I want to make a Dracula theme either way :P

**Comment by ohadnav** [comment]
https://snag.gy/YvR8S1.jpg

**Comment by ohadnav** [comment]
https://snag.gy/YvR8S1.jpg

**Comment by sirrodgepodge** [comment]
Woah yea that’s bad, OS and terminal you’re using?

**Comment by ohadnav** [comment]
MacOS, using iTerm & IntelliJ terminal - both of which have black bg

**Comment by sirrodgepodge** [comment]
got it, will look into it tonight or this weekend

**Comment by sirrodgepodge** [comment]
okay, so clearly very late here (had a baby, started new job, other excuses lol), but did my best to compensate for it by adding full theming flexibility (can easily add new ones with PRs) and added a bunch of themes!

I'm really hoping that at least one of these themes will work for you, let me know!

**Comment by ohadnav** [comment]
Greaaaaaaaaatzz!! 👏👏

**Comment by sirrodgepodge** [comment]
haha I will take it that you're all set then :), thank you!
