### ISSUE TITLE
Any chance we can have an option to save the req and res to MongoDB?

### ISSUE THREAD

**Issue by balexandre** [sirrodgepodge/morgan-body#15]
It would be very useful, for production, to actually save the request and response to a database ...

for this to work even better, we should also add an ID to the request (header name could be in a `options` for easy override):

```javascript
app.use((req, res, next) => {
    const uuid = uuidv1();
    req.id = uuid;
    res.headers['X-Request-Id'] = uuid;
    next();
});
```

and then save it all parameters for the request and response (like you are showing in console) to mongoDB.

**Comment by sirrodgepodge** [comment]
ah sure, so the option would be something like:
```js
{
  ...,
  additionalHeaders: <Array>,
  ...
}
```

**Comment by balexandre** [comment]
sure, maybe a new package then, maybe called something like `morgan-body-mongodb`

it's a bit out of my scope to actually develop such a thing... I'll keep trying to find if there's something I can "plug-in" to save req and responses to a database, as I need a way to keep the information for a given support request of a "why was my information wrong"...

**Comment by sirrodgepodge** [comment]
hey @balexandre, thanks again for your issue.  It raises an interesting point, I think logging is an area for innovation.

Was your search for a tool to suit your needs fruitful?  If so please share!

I'm going to close this as I think handling log persistence is a separate problem (though a good one).

**Comment by balexandre** [comment]
Hi @sirrodgepodge, 

I keep looking.

I just wanted a way to easily attach to code and that would save me the request and request id, so I can provide better support when something goes awire ... I would just ask for the `X-Request-Id` and see what request data was provided for such call ... and say exactly what happened and why.

but, no, some other features started to be in pipeline and I never get back to log requests :(
