### ISSUE TITLE
can you add the IP the request is coming from ?

### ISSUE THREAD

**Issue by eladrkatz** [sirrodgepodge/morgan-body#18]

**Comment by sirrodgepodge** [comment]
Will look into this (would be optional).  There’s a current PR that I need to dive into and write tests for which I think might cover this, hoping to find time to do so soon

**Comment by adams-family** [comment]
I would like that as well, was just thinking about it :)

**Comment by sirrodgepodge** [comment]
unfortunately I don't have time to work on this right now to the extent it deserved (this project is used quite a bit and needs to be tested) :(, I would gladly review a PR

**Comment by VottusCode** [comment]
I've noticed that the IP is still not getting logged.
Internally, I have a fork of morgan-body with this feature, so I may PR later, if I find some time ;) 

I really like morgan-body 👍

**Comment by sirrodgepodge** [comment]
@VottusCode awesome! this would be super great, it's so bothered me that I haven't been able to get to this

**Comment by VottusCode** [comment]
Yes,
I haven't got much time lately, but after I get some, I'll cleanup my fork and PR 😀

**Comment by sirrodgepodge** [comment]
@VottusCode thank you so much!

@eladrkatz @adams-family it's live in `2.5.1` (flag is `logIP`)
