### ISSUE TITLE
index.d.ts not included in npm package

### ISSUE THREAD

**Issue by faustinoribeiro** [sirrodgepodge/morgan-body#20]
index.d.ts is not included in npm package. Add to .npmignore?

**Comment by sirrodgepodge** [comment]
I need to do an NPM release, apologies, will do tonight

**Comment by faustinoribeiro** [comment]
No problem. I will probably create a couple of suggestions (and perhaps something that looks like a bug) down the road.

**Comment by sirrodgepodge** [comment]
okay, finally actually did that thing I said I'd do :), TS in 2.4.6

please let me know any of your thoughts/suggestions, would love to hear

**Comment by canvural** [comment]
Using 2.4.6, it's still not there.

**Comment by sirrodgepodge** [comment]
hm @canvural thank you for letting me know, please send me demo code of how you're trying to import

**Comment by faustinoribeiro** [comment]
I updated to the new version in my project and I can confirm that index.d.ts is still not included the file is missing in node_modules/morgan-body folder). As I previously commented, perhaps adding !index.d.ts in .npmignore can solve the issue (I am not familiar with .npmignore, so it is just a suggestion).

**Comment by canvural** [comment]
> hm @canvural thank you for letting me know, please send me demo code of how you're trying to import

`import morganBody from 'morgan-body';`

**Comment by sirrodgepodge** [comment]
agh shiza @faustinoribeiro you're right, forgot I'm doing "exclude everything but then include this" for the .npmignore here, @canvural should work now 2.4.7 😭

**Comment by canvural** [comment]
@sirrodgepodge I can confirm 2.4.7 has the file. Thank you!

**Comment by sirrodgepodge** [comment]
awesome, thank you!
