### ISSUE TITLE
Hide sensitive data

### ISSUE THREAD

**Issue by Xosmond** [sirrodgepodge/morgan-body#21]
Hello

Thanks for this project, Is there any way to make a Regex to hide sensitive data like tokens or passwords?

**Comment by sirrodgepodge** [comment]
glad you like it!

great idea, how do you think it should be handled?  

Perhaps could list specific keys on the request body and/or response body which should be converted to "•"?

**Comment by sirrodgepodge** [comment]
hey there @Xosmond, wanted to follow up on this, on principle I agree with the idea, need to figure out how to do it properly

**Comment by Xosmond** [comment]
@sirrodgepodge Hello, actually I just make a list of paths, like login and so on to avoid the logging in those cases. I would be better to make a regex to hide json parameters like password and transform "somepassword" to "***" but I didn't have time to do that.

**Comment by spyndutz** [comment]
I think the implementation is to add an option (something like requestBodyException) which accept array parameter contain the list of sensitive keys (the values of the array could be string or regex). Then convert the sensitive keys to (*) with their respective length?

**Comment by joeyfigaro** [comment]
Any movement on this?

**Comment by sirrodgepodge** [comment]
Thanks to @olvis this is done here: https://github.com/sirrodgepodge/morgan-body/pull/27

:)
