### ISSUE TITLE
README.md does not document all options

### ISSUE THREAD

**Issue by Passiday** [sirrodgepodge/morgan-body#25]
I was looking for a way to log headers and, luckily, your last commit message contained reference to headers. So I looked into code and found that there exist very useful `logAllReqHeader`, `logAllResHeader`, `logReqHeaderList` and `logResHeaderList` options. I just wanted to point out that they are not mentioned in your README.

**Comment by sirrodgepodge** [comment]
good catch, definitely meant to add, will add, thank you :)

**Comment by sirrodgepodge** [comment]
done, thank you!
