### ISSUE TITLE
log response body when using express.Router

### ISSUE THREAD

**Issue by kenhuang** [sirrodgepodge/morgan-body#29]
Thanks for this library.

Is there a way to log response body with `express.Router`?

**Comment by sirrodgepodge** [comment]
Thank you for pointing this out, I actually didn't realize that this didn't happen right now.

I'm 90% sure what you'd need to do I believe is overwrite `app.use` inside of this block, check if a `Router` instance was being passed in, and then apply the same `app.response.send` override to the `Router` instance:
https://github.com/sirrodgepodge/morgan-body/blob/master/index.js#L343

I don't have time to try this and test it myself but happy to take the PR if you do.

**Comment by VottusCode** [comment]
@sirrodgepodge @kenhuang Actually, it works with express.Router; I use it, and it works just fine.
I've had the same issue before, all you need to do is register morgan-body before the router.

This way it works for me (controller.registerControllers() under the hood just does router.use to all controller routers)
![Image](https://user-images.githubusercontent.com/53915302/90245580-3c9f6980-de33-11ea-8234-cd26cda3a46e.png)

**Comment by sirrodgepodge** [comment]
@VottusCode thank you so much for sharing!

This is a super creative use of this library (two loggers, one for file, one for console), love it, thinking about adding it as an example...

**Comment by VottusCode** [comment]
thank you 🥰
