### ISSUE TITLE
Is it possible to disable log user-agent?

### ISSUE THREAD

**Issue by serge-nikitin** [sirrodgepodge/morgan-body#3]
I'd like to have an option to disable User Agent info from logs.

P.S. It's really "Logging the way you always wanted it to be!". Thanks!

**Comment by sirrodgepodge** [comment]
Aw thanks man, k, I'll make it an option

**Comment by sirrodgepodge** [comment]
okay, update to `0.10.8` and it has been done :), let me know if there are any other features you'd like!

**Comment by serge-nikitin** [comment]
@sirrodgepodge , it works, thanks!

P.S. Your logger can be really useful for GraphQL requests. I haven't found any such logger. Now it logs requests as a string, like this:
```
{
	"query": "\n  mutation createPost($title: String!, $description: String!) {\n    createPost(title: $title, description: $description)\n  }  \n  ",
	"variables": {
		"title": "title of post",
		"description": "description of post"
	}
}
```

But with formatting JSON data it can looks much better. 

When I finish my learning repository for React + Express + GraphQL, I'll give you a link on it. You will see how it works with your logger and how it can be useful to pretty format JSON data.

**Comment by sirrodgepodge** [comment]
great idea!  That seems like it could prompt a whole rebranding lol.  It wouldn't be a JSON parser (GraphQL is JSON-like but different), you would just need to unescape the newlines and such that are already in the string, could be slightly difficult, not too bad though I don't think.

Do the responses look normal or those are fancy too?
