### ISSUE TITLE
What is the meaning of [-] at the front?

### ISSUE THREAD

**Issue by rain-axb** [sirrodgepodge/morgan-body#31]
and can I hide it?

**Comment by sirrodgepodge** [comment]
![image](https://user-images.githubusercontent.com/7177292/90018798-79286500-dc7b-11ea-9507-bc3075f2e2d4.png)
^That's added in anticipation of you having `req.id` (identifier for your requests in your log)

**Comment by sirrodgepodge** [comment]
right now there's no way to hide it, I think we could add an option to do that, does that sound good?

**Comment by sirrodgepodge** [comment]
okay thank you for this, excluding now by default (can be added back with `logRequestId` option).

this change is in `2.5.0`

**Comment by rain-axb** [comment]
Oh! Thank you so much. I'm using it very well. 👍
