### ISSUE TITLE
Error in Typescript typings. `declare module "morgan-body"` duplicate.

### ISSUE THREAD

**Issue by N8th8n8el** [sirrodgepodge/morgan-body#38]
For some reason the `index.d.ts` contains two module declarations with the same name:

```ts
declare module "morgan-body";

declare module "morgan-body" {
   //...
}
```

This causes any import of `morganBody` to be of type `any` as e.g. `ESLint` reports: `ESLint: Unsafe call of an any typed value.`
It works for me when removing the first module declaration (Or both and just use top level exports).

**Comment by sirrodgepodge** [comment]
got it, fixed in `2.5.2` thank you
