### ISSUE TITLE
Log request datetime in timezone other than GMT

### ISSUE THREAD

**Issue by coderkd10** [sirrodgepodge/morgan-body#4]
Is it possible to log the request datetime formatted to a different timezone (say IST) instead of showing it in GMT. It'll be much easier to quickly make sense from glancing at the logs.

**Comment by sirrodgepodge** [comment]
As of version `0.10.13` this has been added, see `dateTimeFormat` in now in README.

Thank you for the feature request!

**Comment by coderkd10** [comment]
Hi @sirrodgepodge thanks for your awesome project!

Actually I wanted the ability to see the request time in my timezone (IST, i.e, Indian Standard Time). Right now what I see in the logs as time is `Thu, 19 Oct 2017 05:46:37 GMT`, and then I have to mentally add 5.5 hrs to it to get an idea of when the request was made (i.e, around 11 in the morning). Since both I and almost all audience of website are based of India, representing time in IST makes more sense.

But your recent commits have helped me understand the code a bit better, and I feel that I can add this feature myself! So I have forked your project and started hacking on it. I'll try to send a pull request by today / tomorrow. Thanks!

**Comment by coderkd10** [comment]
I've created PR #5 for solving this. I tested it on my local machine and now I'm able to log time in IST yay!

**Comment by sirrodgepodge** [comment]
Merged in your PR, also made some additional changes to handle formatting, they're all in this commit: https://github.com/sirrodgepodge/morgan-body/commit/0db6b031a519ea01851d2162bca24cedb8b00ff4

If you could double check that your use case still works as you expect it to I would much appreciate it and we can close the issue :)
