### ISSUE TITLE
Issue with Logs appeneding

### ISSUE THREAD

**Issue by mast7860** [sirrodgepodge/morgan-body#41]
while using    prettify:false,

The logs gets appended to each other instead of starting in new line

Request: GET /v1/abd heaaders[trace-id=7;content-type=application/json;host=localhost:9085;accept-encoding=gzip, deflate, br;connection=keep-alive] at Thu Oct 15 2020 13:02:41 GMT+0200, IP: ::1, User Agent: PostmanRuntime/7.26.5Response: 404 10.625 ms **Request: GET /v1/abd heaaders[trace-id=7;content-type=application/json;host=localhost:9085;accept-encoding=gzip, deflate, br;connection=keep-alive] at Thu Oct 15 2020 13:02:45 GMT+0200, IP: ::1, User Agent: PostmanRuntime/7.26.5Response: 404 10.625 ms**

Ideally the second log should come in new line .

**Comment by mast7860** [comment]
Looks like I cant create a branch and pull .
The changes will add default line separator for every request.
 
function logger.
line 483 :    '
existing :    var lineSeparator = opts.prettify === true ? '\n' : '';
update :     var lineSeparator = '\n';

**Comment by sirrodgepodge** [comment]
you can't do a fork?  Would love a PR for this, needs separate option to keep newLines even if prettify is false

**Comment by mast7860** [comment]
sure . can create a fork  and have a PR

**Comment by mast7860** [comment]
PR created for the fix

**Comment by sirrodgepodge** [comment]
merged in `2.6.0` thank you!
