### ISSUE TITLE
[Question] How to insert spaces between sections?

### ISSUE THREAD

**Issue by kkocel** [sirrodgepodge/morgan-body#48]
I would like to have spaces between log sections.

My current output:
```
 POST /foo at 2021-02-11T13:10:53.944ZRequest Body...
```
Desired output:
```
 POST /foo at 2021-02-11T13:10:53.944Z Request Body...
```

my config: 
```ts
morganBody(expressApp, {
  prettify: false,
  maxBodyLength: 150_000,
  dateTimeFormat: "iso",
  timezone: "utc",
  noColors: true,
  logReqUserAgent: false,
  logIP: false
});
````

Is there any way I can configure morgan-body to achieve this effect?

**Comment by sirrodgepodge** [comment]
hmmmm I like this, it's how it should be... I'd be fine changing to this and bumping minor vesion.  I don't actually have time to do it right now, here's the two places you'd need to change @kkocel (for either one or both of these you'd need to change `''` to `' '` and update tests)

`var lineSeparator = prettify === true ? separatorStr : '';`

```
function getLineSeperator(includeNewLine){
  if (includeNewLine){
    return '\n';
  } else {
    return '';
  }
}
```

**Comment by kkocel** [comment]
@sirrodgepodge I submitted PR for that
