### ISSUE TITLE
Idea - setup CI for project

### ISSUE THREAD

**Issue by kkocel** [sirrodgepodge/morgan-body#55]
Maybe it will be a good idea to have ci that will run tests on each PR? Eg. Travis CI or similar?

**Comment by sirrodgepodge** [comment]
@VottusCode tried to set up Circle CI at one point, the thing that didn’t work in that env (but does work locally) is that the tests are overriding the date object (to standardize the time)

**Comment by kkocel** [comment]
Maybe it was because of timezone issue?

**Comment by sirrodgepodge** [comment]
that... could totally have been it

**Comment by kkocel** [comment]
@sirrodgepodge I checked and now it passes on CircleCI using your config: https://github.com/sirrodgepodge/morgan-body/blob/master/.circleci/config.yml

**Comment by VottusCode** [comment]
@sirrodgepodge I did fix the CI in #52 so now CI passes.

**Comment by kkocel** [comment]
ok! thanks!
