### ISSUE TITLE
Logging to a file?

### ISSUE THREAD

**Issue by HackintoshMan** [sirrodgepodge/morgan-body#7]
Looking through the code, it doesn't apple that we can access Morgan and insert a stream parameter. Is this something we can get added?

**Comment by sirrodgepodge** [comment]
okay, what I think makes the most sense to do is turn the body logging into a morgan format as at that point all normal morgan options can just be passed along to `morgan-body`

**Comment by HackintoshMan** [comment]
Awesome, I appreciate it!

**Comment by sirrodgepodge** [comment]
and done!
https://github.com/sirrodgepodge/morgan-body/pull/9

**Comment by sirrodgepodge** [comment]
now in 2.2 on NPM

**Comment by HackintoshMan** [comment]
Thank you very much! I'll have to give it a try this afternoon!

**Comment by sirrodgepodge** [comment]
:)
